// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v3.1.1
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:148

#ifndef _TAO_IDL_TESTDATATYPESUPPORTC_NXA0BT_H_
#define _TAO_IDL_TESTDATATYPESUPPORTC_NXA0BT_H_


#include /**/ <ace/config-all.h>

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include <tao/ORB.h>
#include <tao/SystemException.h>
#include <tao/Basic_Types_IDLv4.h>
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace CORBA
{
  using namespace IDLv4;
}

TAO_END_VERSIONED_NAMESPACE_DECL

#include <tao/ORB_Constants.h>
#include <dds/DCPS/ZeroCopyInfoSeq_T.h>
#include <dds/DCPS/ZeroCopySeq_T.h>
#include <tao/Object.h>
#include <tao/String_Manager_T.h>
#include <tao/Sequence_T.h>
#include <tao/Objref_VarOut_T.h>
#include <tao/Seq_Var_T.h>
#include <tao/Seq_Out_T.h>
#include <tao/Arg_Traits_T.h>
#include <tao/Basic_Arguments.h>
#include <tao/Special_Basic_Arguments.h>
#include <tao/Any_Insert_Policy_T.h>
#include <tao/Fixed_Size_Argument_T.h>
#include <tao/Var_Size_Argument_T.h>
#include <tao/UB_String_Arguments.h>
#include /**/ <tao/Version.h>
#include /**/ <tao/Versioned_Namespace.h>

#include "TestDataC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 3 || TAO_MINOR_VERSION != 1 || TAO_MICRO_VERSION != 1
#error This file should be regenerated with TAO_IDL
#endif
// TAO_IDL - Generated from
// /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:34

namespace HelloWorldData
{

  
  // TAO_IDL - Generated from
  // /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp:98

  

  typedef ::TAO::DCPS::ZeroCopyDataSeq< HelloWorldData::Msg, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> MsgSeq;
  
  // TAO_IDL - Generated from
  // /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:742

  

#if !defined (_HELLOWORLDDATA_MSGTYPESUPPORT__VAR_OUT_CH_)
#define _HELLOWORLDDATA_MSGTYPESUPPORT__VAR_OUT_CH_

  class MsgTypeSupport;
  using MsgTypeSupport_ptr = MsgTypeSupport*;
  using MsgTypeSupport_var = TAO_Objref_Var_T<MsgTypeSupport>;
  using MsgTypeSupport_out = TAO_Objref_Out_T<MsgTypeSupport>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  MsgTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:
    // TAO_IDL - Generated from
    // /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:296

    using _ptr_type = MsgTypeSupport_ptr;
    using _var_type = MsgTypeSupport_var;
    using _out_type = MsgTypeSupport_out;

    // The static operations.
    static MsgTypeSupport_ptr _duplicate (MsgTypeSupport_ptr obj);

    static void _tao_release (MsgTypeSupport_ptr obj);

    static MsgTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static MsgTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static MsgTypeSupport_ptr _nil ();

    virtual ::DDS::ReturnCode_t encode_to_string (
      const ::HelloWorldData::Msg & sample,
      ::CORBA::String_out encoded,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t encode_to_bytes (
      const ::HelloWorldData::Msg & sample,
      ::DDS::OctetSeq_out encoded,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t decode_from_string (
      const char * encoded,
      ::HelloWorldData::Msg_out sample,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t decode_from_bytes (
      const ::DDS::OctetSeq & encoded,
      ::HelloWorldData::Msg_out sample,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    
    // TAO_IDL - Generated from
    // /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    MsgTypeSupport ();

    

    virtual ~MsgTypeSupport () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    MsgTypeSupport (const MsgTypeSupport &) = delete;
    MsgTypeSupport (MsgTypeSupport &&) = delete;
    MsgTypeSupport &operator= (const MsgTypeSupport &) = delete;
    MsgTypeSupport &operator= (MsgTypeSupport &&) = delete;
  };
  // TAO_IDL - Generated from
  // /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:742

  

#if !defined (_HELLOWORLDDATA_MSGDATAWRITER__VAR_OUT_CH_)
#define _HELLOWORLDDATA_MSGDATAWRITER__VAR_OUT_CH_

  class MsgDataWriter;
  using MsgDataWriter_ptr = MsgDataWriter*;
  using MsgDataWriter_var = TAO_Objref_Var_T<MsgDataWriter>;
  using MsgDataWriter_out = TAO_Objref_Out_T<MsgDataWriter>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  MsgDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:
    // TAO_IDL - Generated from
    // /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:296

    using _ptr_type = MsgDataWriter_ptr;
    using _var_type = MsgDataWriter_var;
    using _out_type = MsgDataWriter_out;

    // The static operations.
    static MsgDataWriter_ptr _duplicate (MsgDataWriter_ptr obj);

    static void _tao_release (MsgDataWriter_ptr obj);

    static MsgDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static MsgDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static MsgDataWriter_ptr _nil ();

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::HelloWorldData::Msg & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::HelloWorldData::Msg & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::HelloWorldData::Msg & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::HelloWorldData::Msg & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::HelloWorldData::Msg & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::HelloWorldData::Msg & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::HelloWorldData::Msg & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::HelloWorldData::Msg & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::HelloWorldData::Msg & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::HelloWorldData::Msg & instance_data) = 0;

    
    // TAO_IDL - Generated from
    // /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    MsgDataWriter ();

    

    virtual ~MsgDataWriter () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    MsgDataWriter (const MsgDataWriter &) = delete;
    MsgDataWriter (MsgDataWriter &&) = delete;
    MsgDataWriter &operator= (const MsgDataWriter &) = delete;
    MsgDataWriter &operator= (MsgDataWriter &&) = delete;
  };
  // TAO_IDL - Generated from
  // /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:742

  

#if !defined (_HELLOWORLDDATA_MSGDATAREADER__VAR_OUT_CH_)
#define _HELLOWORLDDATA_MSGDATAREADER__VAR_OUT_CH_

  class MsgDataReader;
  using MsgDataReader_ptr = MsgDataReader*;
  using MsgDataReader_var = TAO_Objref_Var_T<MsgDataReader>;
  using MsgDataReader_out = TAO_Objref_Out_T<MsgDataReader>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  MsgDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:
    // TAO_IDL - Generated from
    // /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:296

    using _ptr_type = MsgDataReader_ptr;
    using _var_type = MsgDataReader_var;
    using _out_type = MsgDataReader_out;

    // The static operations.
    static MsgDataReader_ptr _duplicate (MsgDataReader_ptr obj);

    static void _tao_release (MsgDataReader_ptr obj);

    static MsgDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static MsgDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static MsgDataReader_ptr _nil ();

    virtual ::DDS::ReturnCode_t read (
      ::HelloWorldData::MsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::HelloWorldData::MsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::HelloWorldData::MsgSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::HelloWorldData::MsgSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::HelloWorldData::Msg & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::HelloWorldData::Msg & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::HelloWorldData::MsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::HelloWorldData::MsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::HelloWorldData::MsgSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::HelloWorldData::MsgSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::HelloWorldData::MsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::HelloWorldData::MsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::HelloWorldData::MsgSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::HelloWorldData::MsgSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::HelloWorldData::MsgSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::HelloWorldData::Msg & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::HelloWorldData::Msg & instance_data) = 0;

    
    // TAO_IDL - Generated from
    // /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    MsgDataReader ();

    

    virtual ~MsgDataReader () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    MsgDataReader (const MsgDataReader &) = delete;
    MsgDataReader (MsgDataReader &&) = delete;
    MsgDataReader &operator= (const MsgDataReader &) = delete;
    MsgDataReader &operator= (MsgDataReader &&) = delete;
  };


// TAO_IDL - Generated from
// /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:62


} // module HelloWorldData
// TAO_IDL - Generated from
// /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_traits.cpp:58



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_HELLOWORLDDATA_MSGTYPESUPPORT__TRAITS_)
#define _HELLOWORLDDATA_MSGTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::HelloWorldData::MsgTypeSupport>
  {
    static ::HelloWorldData::MsgTypeSupport_ptr duplicate (::HelloWorldData::MsgTypeSupport_ptr p);
    static void release (::HelloWorldData::MsgTypeSupport_ptr p);
    static ::HelloWorldData::MsgTypeSupport_ptr nil ();
    static ::CORBA::Boolean marshal (const ::HelloWorldData::MsgTypeSupport_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_HELLOWORLDDATA_MSGDATAWRITER__TRAITS_)
#define _HELLOWORLDDATA_MSGDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::HelloWorldData::MsgDataWriter>
  {
    static ::HelloWorldData::MsgDataWriter_ptr duplicate (::HelloWorldData::MsgDataWriter_ptr p);
    static void release (::HelloWorldData::MsgDataWriter_ptr p);
    static ::HelloWorldData::MsgDataWriter_ptr nil ();
    static ::CORBA::Boolean marshal (const ::HelloWorldData::MsgDataWriter_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_HELLOWORLDDATA_MSGDATAREADER__TRAITS_)
#define _HELLOWORLDDATA_MSGDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::HelloWorldData::MsgDataReader>
  {
    static ::HelloWorldData::MsgDataReader_ptr duplicate (::HelloWorldData::MsgDataReader_ptr p);
    static void release (::HelloWorldData::MsgDataReader_ptr p);
    static ::HelloWorldData::MsgDataReader_ptr nil ();
    static ::CORBA::Boolean marshal (const ::HelloWorldData::MsgDataReader_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1648

#endif /* ifndef */

