// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v3.1.1
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "TestDataC.h"
#include <tao/CDR.h>
// TAO_IDL - Generated from
// /home/mhutomop/OpenDDS-3.26.1/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_cs.cpp:48


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const HelloWorldData::Msg &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.user_id) &&
    (strm << _tao_aggregate.message.in ());
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    HelloWorldData::Msg &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.user_id) &&
    (strm >> _tao_aggregate.message.out ());
}

TAO_END_VERSIONED_NAMESPACE_DECL



